// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqfOFhLiU2wGNzuBQMjz3NbcIbdzEk_Io',
    appId: '1:516564451945:web:b0875e86983bdbaabe18f8',
    messagingSenderId: '516564451945',
    projectId: 'studentdatabaseproject-5433d',
    authDomain: 'studentdatabaseproject-5433d.firebaseapp.com',
    storageBucket: 'studentdatabaseproject-5433d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiT5nU1vmOTWTbcofg3XkMIZDwlA2zDWA',
    appId: '1:516564451945:android:4a31882270fa8ab5be18f8',
    messagingSenderId: '516564451945',
    projectId: 'studentdatabaseproject-5433d',
    storageBucket: 'studentdatabaseproject-5433d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiqfZw0lgW6jOivD5W2QwQ8MHH25xHLAw',
    appId: '1:516564451945:ios:4e54a15ae6cb6e14be18f8',
    messagingSenderId: '516564451945',
    projectId: 'studentdatabaseproject-5433d',
    storageBucket: 'studentdatabaseproject-5433d.appspot.com',
    iosBundleId: 'com.example.studentdatabaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiqfZw0lgW6jOivD5W2QwQ8MHH25xHLAw',
    appId: '1:516564451945:ios:4e54a15ae6cb6e14be18f8',
    messagingSenderId: '516564451945',
    projectId: 'studentdatabaseproject-5433d',
    storageBucket: 'studentdatabaseproject-5433d.appspot.com',
    iosBundleId: 'com.example.studentdatabaseproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqfOFhLiU2wGNzuBQMjz3NbcIbdzEk_Io',
    appId: '1:516564451945:web:7b2a0044a146b0e4be18f8',
    messagingSenderId: '516564451945',
    projectId: 'studentdatabaseproject-5433d',
    authDomain: 'studentdatabaseproject-5433d.firebaseapp.com',
    storageBucket: 'studentdatabaseproject-5433d.appspot.com',
  );
}
